### PR TITLE
Display Weather data on home page

### LINKED ISSUE #2: Get data from API
Website = https://openweathermap.org/api
Get data from Open Weather Map and display it on Home page.

### PR DESCRIPTION
**Pull request by 2802harsh**
# Changes Made
- city name updated in App.js when corresponding change takes place in GetLocation comp
- Get request made in App.js to update weather data of particular location using useEffect hook
- Fixes #2 

# Screenshot
Screenshot from 2020-10-11 16-47-17

### CODE REVIEW

**Comment by garvitchittora** [comment]
@2802harsh bro nice work but can you add more details like temp., humidity, etc.

**Comment by 2802harsh** [comment]
Sure. On it.

**Comment by infern018** [comment]
@2802harsh, pls attach a SS of further changes

**Comment by 2802harsh** [comment]
@garvitchittora @infern018  Please review the changes.
Here is the screenshot of the new changes:
Screenshot from 2020-10-11 19-38-02

**Comment by infern018** [comment]
Good work @2802harsh

**Pull request merged**
