### PR TITLE
added footer issue no- #13

### PR DESCRIPTION
**Pull request by cosmoimai**
photo
I have added a footer in which the icon of Github contains a link that redirects you to this repo. I have also added a link to the API in the route section I created an empty link that redirects you to Home, Search, and Subscribe.

### CODE REVIEW

**Comment by infern018** [comment]
pls attach a ss of your changes

**Comment by cosmoimai** [comment]
You mean that files that I have added or how the site looks with footer?

**Comment by infern018** [comment]
yes, how the footer looks

**Comment by cosmoimai** [comment]
@infern018  is it visible I have uploaded.

**Pull request closed without merging**
