### PR TITLE
added navbar succesfully using css

### PR DESCRIPTION
**Pull request by Parasagrawal**
saccesfully added buttons, so that user can  search city by name, go to home directly or to Subscribe (recieve email every day about weather in the given location)

### CODE REVIEW

**Comment by infern018** [comment]
Pls resolve conflicts @Parasagrawal

**Comment by Parasagrawal** [comment]
@infern018 updated

**Comment by infern018** [comment]
Pls attach ss of changes

**Comment by Parasagrawal** [comment]
Screen Shot 2020-10-12 at 23 04 37
Screen Shot 2020-10-12 at 23 05 09
Screen Shot 2020-10-12 at 23 05 20

**Pull request merged**
