### PR TITLE
added model user to subscribe app

### LINKED ISSUE #15: Create django Model
Create a Django model name "User" in the Django app named "Subscribe" which contains fields like "email", "city" and "name".

### PR DESCRIPTION
**Pull request by Capt-Titanium**
Fixes #15 
created django model User in app Subscribe with fields - name, city and email address

### CODE REVIEW

**Comment by garvitchittora** [comment]
@Capt-Titanium can you plz attach ss of the database.

**Comment by Capt-Titanium** [comment]
I have not registered the model in admin.py hence I did not open it using "/admin" page in the server. But I have some screenshots using the SQLite browser.
Capture1
Capture2

**Comment by infern018** [comment]
@garvitchittora  pls review

**Comment by garvitchittora** [comment]
Hi @Capt-Titanium, you need to register this model in admin.py also, plz register that and then comment with the ss of the admin panel :).

**Comment by Capt-Titanium** [comment]
Heyy @garvitchittora , registered the model now! 
Capture3
Capture4
Capture5

**Pull request merged**
