### PR TITLE
Created the subscribe page.

### LINKED ISSUE #8: Send Email Form on subscribe page
## Send Email Form
Send email form on subscribe page

### PR DESCRIPTION
**Pull request by sandy9808**
Fixes #8

The Subscribe component of the web app is now done.

Screenshots : 
image

image

### CODE REVIEW

**Comment by garvitchittora** [comment]
Hi @sandy9808, can you plz make a live link of your repo on (https://codesandbox.io/) and send it.

**Comment by sandy9808** [comment]
https://app.netlify.com/sites/tender-spence-68d718/deploys/5f82abcf9559f9bfcf1b56bd

**Comment by sandy9808** [comment]
> Hi @sandy9808, can you plz make a live link of your repo on (https://codesandbox.io/) and send it.

The 404 error page is showing up on opening the route '/subscribe' in the deployed website on netlify. I might be deploying it incorrectly maybe. Please help me out.

**Comment by garvitchittora** [comment]
[live link](https://hk8it.csb.app/)

**Comment by garvitchittora** [comment]
change class with className in index.js in subscribe component and your background is not visible plz check.

**Comment by garvitchittora** [comment]
@sandy9808 can you plz resolve this conflict.

**Comment by sandy9808** [comment]
I will make a new pull request, too many conflicts to handle.

**Pull request closed without merging**
