### PR TITLE
Fixes issue#3 Added Search page frontend.

### PR DESCRIPTION
**Pull request by AlacritousCreature**
issue #3

Added search form in search.js
view it [here](https://fxlol.csb.app/search) on sandbox.

### CODE REVIEW

**Comment by infern018** [comment]
Nice UI, good work @AlacritousCreature 🎉
Screenshot 2020-10-11 211205
please fix this overlapping of text issue, the placeholder should not be displayed while typing...

**Comment by AlacritousCreature** [comment]
Thanks! :)..... I'll fix it.

**Comment by AlacritousCreature** [comment]
Hey! actually after making pr I had made some changes there on sandbox...now I have made it same.....please once [view](https://fxlol.csb.app/search) it here.

**Comment by infern018** [comment]
cool, works fine, commit the changes

**Comment by AlacritousCreature** [comment]
its the same which I commited :sweat_smile:...after making the pr I had tried make it placeholder, so it was like that on that sandbox link.

**Comment by AlacritousCreature** [comment]
Thanks!

**Pull request merged**
